import {regions,motionScore,Trigger} from './detector.mjs';
const $=id=>document.getElementById(id),video=$('video'),canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true}),trigger=new Trigger();canvas.width=96;canvas.height=72;
let stream,audio,wake,previous,timer,running=false,starting=false,generation=0,started=0,count=0,flashTimer;
function message(text){$('status').textContent=text}function error(text){$('error').textContent=text;$('error').hidden=!text}
async function unlock(){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw new Error('このブラウザは音声再生に対応していません。Safari または Chrome で開いてください。');audio??=new Audio();await audio.resume();if(audio.state!=='running')throw new Error('音声を開始できませんでした。もう一度「チャイムの音を確認」を押してください。')}
function chime(){if(!audio||audio.state!=='running'){error('音声が一時停止しています。「チャイムの音を確認」を押して音声を再開してください。');return}const t=audio.currentTime;[880,659.25].forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain(),at=t+i*.32;o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(Number($('volume').value)/100*.32,at+.015);g.gain.exponentialRampToValueAtTime(.0001,at+.85);o.connect(g);g.connect(audio.destination);o.start(at);o.stop(at+.9);o.onended=()=>{o.disconnect();g.disconnect()}})}
function layout(){if(!video.videoWidth)return;const box=video.getBoundingClientRect(),scale=Math.min(box.width/video.videoWidth,box.height/video.videoHeight),w=video.videoWidth*scale,h=video.videoHeight*scale,[x,y,rw,rh]=regions[$('area').value];Object.assign($('region').style,{left:`${(box.width-w)/2+x*w}px`,top:`${(box.height-h)/2+y*h}px`,width:`${rw*w}px`,height:`${rh*h}px`})}
async function keepAwake(){try{if(navigator.wakeLock)wake=await navigator.wakeLock.request('screen')}catch{}}
function stop(text='停止しました'){generation++;running=false;starting=false;clearInterval(timer);stream?.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null;video.style.display='none';$('placeholder').style.display='flex';$('region').style.display='none';wake?.release().catch(()=>{});wake=null;$('start').disabled=false;$('start').classList.remove('running');$('start').textContent='カメラを起動して開始';$('badge').textContent='停止中';$('badge').classList.remove('active');$('meter').style.width='0';message(text)}
async function start(){if(running){stop();return}if(starting)return;starting=true;const id=++generation;error('');$('start').disabled=true;message('カメラの使用を許可してください');try{await unlock();if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia)throw new Error('カメラを使うには HTTPS のページを Safari または Chrome で開いてください。');const obtained=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{exact:'environment'},width:{ideal:640},height:{ideal:480},frameRate:{ideal:15,max:20}}});if(id!==generation){obtained.getTracks().forEach(t=>t.stop());return}stream=obtained;video.srcObject=stream;video.style.display='block';await video.play();if(id!==generation)return;running=true;starting=false;document.querySelector('.meter').hidden=false;stream.getVideoTracks()[0].addEventListener('ended',()=>{if(running)stop('カメラが切断されました。もう一度開始してください。')});$('placeholder').style.display='none';$('region').style.display='block';$('start').disabled=false;$('start').textContent='検知を停止する';$('start').classList.add('running');$('badge').textContent='検知中';$('badge').classList.add('active');previous=null;trigger.reset();started=performance.now();layout();keepAwake();timer=setInterval(tick,100);message('準備中… スマホを固定してください');}catch(e){if(id!==generation)return;stop('開始できませんでした');const messages={NotAllowedError:'カメラの使用が許可されていません。ブラウザのサイト設定でカメラを許可して、もう一度開始してください。',NotFoundError:'外カメラが見つかりません。外カメラのあるスマホで開いてください。',OverconstrainedError:'外カメラを利用できません。スマホの Safari または Chrome で開いてください。',NotReadableError:'カメラを使用できません。他のカメラアプリを閉じて再度お試しください。'};error(messages[e.name]||e.message)}}
function tick(){if(!running||video.readyState<2)return;try{const [x,y,w,h]=regions[$('area').value];ctx.drawImage(video,x*video.videoWidth,y*video.videoHeight,w*video.videoWidth,h*video.videoHeight,0,0,96,72);const rgba=ctx.getImageData(0,0,96,72).data,gray=new Float32Array(96*72);for(let i=0;i<gray.length;i++)gray[i]=rgba[i*4]*.299+rgba[i*4+1]*.587+rgba[i*4+2]*.114;const score=motionScore(previous,gray);previous=gray;const now=performance.now(),threshold=[0,.16,.1,.06,.035,.018][Number($('sensitivity').value)];$('meter').style.width=`${Math.min(100,score/threshold*50)}%`;if(now-started<2200)return;const delay=Number($('cooldown').value)*1000;if(trigger.update(score,threshold,now,delay)){chime();$('count').textContent=++count;$('last').textContent='最終検知 '+new Date().toLocaleTimeString('ja-JP');document.querySelector('.monitor').classList.add('flash');clearTimeout(flashTimer);flashTimer=setTimeout(()=>document.querySelector('.monitor').classList.remove('flash'),800)}message(now-trigger.last<delay?'通過を検知 · 次の通知まで '+Math.ceil((delay-now+trigger.last)/1000)+'秒':'検知中 · エリア内の動きを待っています')}catch{stop('映像を読み取れませんでした。再度開始してください。')}}
$('start').onclick=start;$('test').onclick=async()=>{error('');try{await unlock();chime()}catch(e){error(e.message)}};$('sensitivity').oninput=()=>{$('sensitivityValue').value=['','低め','やや低め','標準','やや高め','高め'][$('sensitivity').value];previous=null;trigger.hits=0};$('volume').oninput=()=>{$('volumeValue').value=$('volume').value+'%'};$('area').onchange=()=>{previous=null;trigger.hits=0;started=performance.now();layout()};window.addEventListener('resize',layout);video.addEventListener('resize',layout);document.addEventListener('visibilitychange',()=>{if(document.hidden&&(running||starting))stop('画面を離れたため停止しました。再度開始してください。')});window.addEventListener('pagehide',()=>stop());
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_chime_status',description:'Read camera detection status and the session trigger count.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');return {running,count,status:$('status').textContent}}})).catch(()=>{})}catch{}}


